apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  selector:
    app: sistema-noticias
  ports:
  - port: 80
    # targetPort: <Target Port>
    nodePort: 30001
