apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
  - name: myapp
    image: aluracursos/portal-noticias:1
    ports:
      - containerPort: 80
      # Importando config map
    envFrom:
      - configMapRef:
          name: portal-configmap